1 SC ANTI CURL/S2M YA
CUMA KALO MAU DI CURL SILAHKAN 

2 KONEK PANEL DI konek-pusat-panel.php
TINGAL NARUH LINK AJAH YA PAHAM 

3 INI SC BISA DI JS KALO MAU DI JS PASANG AJAH
SC MASIH MURNI CUY JADI SETTING SENDIRI AJAH

PENGUMUMAN: JIKA RAGU SAMA SC DI CEK AJAH AMAN KAGA YA,SOALNYH UDH BERSIH. MASIH RAGU BERARTI YANTO